#!/usr/bin/env python3
"""Generate the MkDocs site content from the architecture-as-code sources.

Sources (edited by humans or agents):
  bca/engagements/**/model.yaml  one BCA model per engagement
  library/**                     reusable taxonomy, attributes, outcomes

Output (generated, never hand-edited, git-ignored):
  docs/bca/<engagement>.md       one page per engagement (menu builds itself)
  docs/library/*.md              library reference pages

Hand-written docs/bca/index.md and docs/library/index.md are left alone.

Usage: python scripts/build_docs.py
"""
import pathlib, sys
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from render_domain_impact import render  # noqa: E402

DOCS = ROOT / "docs"
GENERATED_DIRS = ("bca", "library")
BANNER = "<!-- Generated by scripts/build_docs.py from source YAML. Do not edit. -->\n\n"


def load(p):
    return yaml.safe_load(open(p, encoding="utf-8"))


def cell(v):
    if v is None:
        return ""
    if isinstance(v, list):
        return ", ".join(str(x) for x in v)
    return str(v).replace("|", "\\|").replace("\n", " ")


def table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return "\n".join(lines) + "\n"


def indent(text, n=4):
    return "".join(" " * n + line + "\n" if line else "\n" for line in text.splitlines())


def strip_front_matter(mmd):
    lines = mmd.splitlines()
    if lines and lines[0].strip() == "---":
        end = lines.index("---", 1)
        lines = lines[end + 1:]
    return "\n".join(lines)


def completeness(m):
    flags = []
    if not m.get("value"):
        flags.append("No value element")
    if any(not b.get("creates_value") for b in m["business_outcomes"]):
        flags.append("A business outcome has no value trace")
    answered = {r for s in m["strategies"] for r in s["mitigates"]} | {
        r["id"] for r in m["risks"] if r.get("strategies")}
    if any(r["id"] not in answered and r["treatment"] != "Accept" for r in m["risks"]):
        flags.append("A risk has no mitigation strategy")
    if not m["scope"].get("out"):
        flags.append("No out-of-scope statements")
    if not m.get("decisions"):
        flags.append("No decisions listed")
    return flags


def attribute_view(m, name):
    """Derive Domain (Attributes) from strategies: the SABSA DOMA view, never hand-written."""
    view = {}
    for s in m["strategies"]:
        for d in s["domains"]:
            for a in s["attributes"]:
                view.setdefault(d, [])
                if a not in view[d]:
                    view[d].append(a)
    return [[name(d), ", ".join(attrs),
             ", ".join(s["id"] for s in m["strategies"] if d in s["domains"])] for d, attrs in view.items()]


def engagement_page(model_path, domains):
    m = load(model_path)
    md, name = m["metadata"], (lambda d: domains.get(d, {}).get("name", d))
    tags = ["bca", f"bca-{md['mode']}", md["status"].lower().replace("_", "-")]
    if m["sda_trigger"]["recommended"]:
        tags.append("sda-recommended")
    s = ["---\ntags:\n" + "".join(f"  - {t}\n" for t in tags) + "---\n\n", BANNER, f"# {md['title']}\n"]

    s.append(table(["ID", "Mode", "Status", "Classification", "Author", "Date"],
                   [[md["id"], md["mode"], md["status"], md["classification"], md["author"], md["date"]]]))
    flags = completeness(m)
    if flags:
        s.append('!!! warning "Incomplete"\n' + "".join(f"    - {f}\n" for f in flags) + "\n")
    else:
        s.append('!!! success "Completeness check passed"\n    Value, outcome traces, risks with strategies, scope, and decisions are present.\n\n')

    s.append("## 1.0 Problem Statement and Value\n")
    p = m["problem"]
    s.append(f"{p['statement']}\n\n- **Current state:** {p['current_state']}\n- **Desired state:** {p['desired_state']}\n\n")
    s.append("**Value created or protected**\n\n")
    s.append(table(["ID", "Domain", "Statement", "Measure"],
                   [[v["id"], name(v["domain"]), v["statement"], v.get("measure", "")] for v in m["value"]]))

    s.append("\n## 2.0 Business Outcomes\n")
    s.append("Necessity levels follow RFC 2119.\n\n")
    s.append(table(["ID", "Outcome", "Necessity", "Value", "Domains", "Evidence"],
                   [[b["id"], f"**{b['name']}**: {b['description']}", b["necessity"], b["creates_value"],
                     [name(d) for d in b["domains"]],
                     "; ".join(f"{e['source']} ({e.get('reference', '')})" for e in b.get("evidence", []))]
                    for b in m["business_outcomes"]]))

    s.append("\n## 3.0 Scope\n\n**In scope**\n\n")
    s += [f"- {i['statement']}\n" for i in m["scope"]["in"]]
    s.append("\n**Out of scope**\n\n")
    s += [f"- {i['statement']}" + (f" *({i['rationale']})*" if i.get("rationale") else "") + "\n" for i in m["scope"]["out"]]

    s.append("\n## 4.0 Domain Impact Worksheet\n\n")
    s.append("Each domain shows the organization's own elements, taken from the inputs. Gold = physical domain, "
             "blue = logical domain. Border weight shows impact; a dashed red border marks a gap that needs a decision.\n\n")
    s.append('=== "Worksheet"\n\n')
    s.append(indent("```mermaid\n" + strip_front_matter(render(m)) + "\n```") + "\n")
    s.append('=== "Relationships"\n\n')
    s.append(indent("```mermaid\n" + strip_front_matter(render(m, "impacted")) + "\n```") + "\n")

    def el(e):
        return f"{e['name']} ({e['source']})" if isinstance(e, dict) and e.get("source") else (e["name"] if isinstance(e, dict) else e)
    rows = [[name(i["domain"]), i["impact"], "; ".join(el(e) for e in i.get("elements", [])),
             "Confirmed" if i.get("confirmed_empty") else ""] for i in m["domain_impact"]]
    s.append('??? note "Domain elements and sources"\n\n')
    s.append("".join("    " + line + "\n" for line in table(["Domain", "Impact", "Elements", "Empty confirmed"], rows).splitlines()))

    strat = {x["id"]: x for x in m["strategies"]}
    def strategies_for(r):
        ids = list(r.get("strategies", [])) + [x["id"] for x in m["strategies"] if r["id"] in x["mitigates"] and x["id"] not in r.get("strategies", [])]
        return ", ".join(ids)
    ranked = sorted(m["risks"], key=lambda r: r.get("rank", 99))
    s.append("\n## 5.0 Risks and Mitigation Strategies\n\n")
    s.append("A threat model at the business-outcome level: the top risks to value across all domains, the strategies "
             "that answer them, and the business attributes that abstract those strategies.\n\n")
    s.append("### 5.1 Top Risks to Value\n\n")
    s.append(table(["Rank", "ID", "Risk", "Domain", "Threatens", "Likelihood", "Impact", "Treatment", "Strategies"],
                   [[r.get("rank", ""), r["id"], r["statement"], name(r["domain"]), r["threatens"], r.get("likelihood", ""),
                     r.get("impact", ""), r["treatment"], strategies_for(r)] for r in ranked]))
    s.append("\n### 5.2 Mitigation Strategies and Attributes\n\n")
    s.append("The attributes abstract each strategy. They become the non-functional requirements of the Conceptual Architecture.\n\n")
    s.append(table(["ID", "Strategy", "Mitigates", "Domains", "Attributes"],
                   [[x["id"], f"**{x.get('name', '')}**: {x['statement']}" if x.get("name") else x["statement"],
                     x["mitigates"], [name(d) for d in x["domains"]], ", ".join(x["attributes"])] for x in m["strategies"]]))
    s.append("\n### 5.3 Attributes by Domain (derived)\n\n")
    s.append("Generated from the strategies above, in SABSA DOMA form: the attributes each domain must exhibit.\n\n")
    s.append(table(["Domain", "Attributes", "From strategies"], attribute_view(m, name)))

    s.append("\n## 6.0 Decisions Required\n")
    s.append(table(["ID", "Question", "Owner", "Status", "ADR"],
                   [[d["id"], d["question"], d["owner"], d["status"], "Yes" if d.get("adr_needed") else ""]
                    for d in m["decisions"]]))
    t_ = m["sda_trigger"]
    s.append("\n**Independent Security Design Assessment**\n\n")
    s.append(f"- **Recommended:** {'Yes' if t_['recommended'] else 'No'}\n")
    s.append(f"- **Basis:** {', '.join(t_['reasons']) or 'Collaboration evidence'}\n")
    if t_.get("notes"):
        s.append(f"- **Notes:** {t_['notes']}\n")

    if m.get("references"):
        s.append("\n## 7.0 References\n\n")
        s += [f"- [{r['title']}]({r['url']})\n" if r.get("url") else f"- {r['title']}\n" for r in m["references"]]

    s.append(f"\n---\n*Source: `{model_path.relative_to(ROOT).as_posix()}`*\n")
    return "".join(s)


def library_pages(domains_doc):
    pages = {}
    doms = domains_doc["domains"]
    byid = {d["id"]: d for d in doms}
    s = [BANNER, "# Baseline Perspective Domains\n\n",
         "Domain model: The Agile Security System™ Baseline Perspectives™, © Archistry / Andrew S. Townley, "
         "used with attribution. Based on SABSA®. Descriptions are paraphrased.\n\n"]
    s.append(table(["ID", "Name", "Type", "Parent", "Description"],
                   [[d["id"], d["name"], d["type"], byid.get(d["parent"], {}).get("name", ""), " ".join(d["description"].split())]
                    for d in doms]))
    pages["library/domains.md"] = "".join(s)

    attrs = load(ROOT / "library/attributes.yaml")
    s = [BANNER, "# Business Attributes\n\n",
         "Attributes qualify how a domain must behave. Pair one with a domain to form a DOMA. "
         "Source set: AEF™ attributes (© Archistry), SABSA® concept (© The SABSA Institute). Definitions paraphrased.\n\n"]
    for cat, desc in attrs["categories"].items():
        rows = [[a["id"], a["definition"]] for a in attrs["attributes"] if a["category"] == cat]
        s.append(f"## {cat.replace('_', ' ').title()}\n\n*{desc}*\n\n" + table(["Attribute", "Definition"], rows) + "\n")
    pages["library/attributes.md"] = "".join(s)

    outs = load(ROOT / "library/business_outcomes.yaml")
    s = [BANNER, "# Business Outcomes Library\n\n",
         "Reusable statements of value created or protected. Solution BCAs reuse these and cite their own evidence.\n\n"]
    for o in outs["outcomes"]:
        ex = o.get("example", {})
        s.append(f"## {o['name']}\n\n`{o['id']}` · {byid[o['value_domain']]['name']}\n\n{o['statement']}\n\n"
                 f"- **Typical domains:** {', '.join(byid[d]['name'] for d in o['typical_domains'])}\n"
                 f"- **Typical attributes:** {', '.join(o['typical_attributes'])}\n"
                 f"- **Evidence sources:** {', '.join(o['evidence_sources'])}\n")
        if ex:
            s.append(f"- **Example ({ex['org']}):** {ex['evidence']} *({ex['ref']})*\n")
        s.append("\n")
    pages["library/business-outcomes.md"] = "".join(s)

    strats = load(ROOT / "library/strategies.yaml")
    s = [BANNER, "# Mitigation Strategies Library\n\n",
         "Reusable answers to risks to value. Each strategy carries the business attributes that abstract it; "
         "those attributes become the Conceptual Architecture's non-functional requirements.\n\n"]
    s.append(table(["ID", "Strategy", "Mitigates", "Attributes", "Typical domains"],
                   [[x["id"], f"**{x['name']}**: {x['statement']}", x["mitigates"], ", ".join(x["attributes"]),
                     ", ".join(byid[d]["name"] for d in x["typical_domains"])] for x in strats["strategies"]]))
    pages["library/strategies.md"] = "".join(s)
    return pages


def main(quiet=False):
    domains_doc = load(ROOT / "library/taxonomy/domains.yaml")
    domains = {d["id"]: d for d in domains_doc["domains"]}

    pages = library_pages(domains_doc)
    for mp in sorted((ROOT / "bca" / "engagements").rglob("model.yaml")):
        slug = mp.parent.relative_to(ROOT / "bca" / "engagements").as_posix().replace("/", "-")
        pages[f"bca/{slug}.md"] = engagement_page(mp, domains)

    # Write only what changed, and remove stale pages, so `mkdocs serve`
    # does not loop on its own output. Hand-written index pages are kept.
    changed = 0
    for rel, text in pages.items():
        dest = DOCS / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists() or dest.read_text(encoding="utf-8") != text:
            dest.write_text(text, encoding="utf-8")
            changed += 1
    for d in GENERATED_DIRS:
        for f in (DOCS / d).glob("*.md"):
            if f.name != "index.md" and f"{d}/{f.name}" not in pages:
                f.unlink()
                changed += 1
    if not quiet:
        print(f"Generated {len(pages)} page(s) in docs/bca and docs/library ({changed} updated)")


if __name__ == "__main__":
    main()
