#!/usr/bin/env python3
"""Render a Domain Impact Worksheet as a Mermaid flowchart from a BCA model.

Usage:
  python scripts/render_domain_impact.py engagements/<name>/model.yaml [--all-edges] [-o out.mmd]

Reads library/taxonomy/domains.yaml for structure and relationships, and the
model's domain_impact section for impact and elements. The worksheet shows
elements only; attributes belong to mitigation strategies, not to domains.
Output is regenerated, never hand-edited.

Visual conventions
  Fill   gold = physical domain, blue = logical domain (Townley convention)
  Border thickness/color = impact (high / medium / low); dashed grey = none
  Dashed red border = GAP: domain not assessed, or 'none' without human confirmation
  Bullets inside a domain = the organization's elements (up to 5; full list in the page table)
  Edges = optional provider -> consumer relationships (--edges impacted|all); off by default
          so the worksheet reads as a heat map, like the PowerPoint original
"""
import argparse, pathlib, sys
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]

FILL = {
    "physical": "fill:#F6D776,stroke:#8A6D1F,color:#222",
    "logical":  "fill:#A9CBEA,stroke:#2F5F8A,color:#222",
    "boundary": "fill:#FFFFFF,stroke:#555,color:#222",
}
CONTAINER = {  # lighter tints so nested domains stay readable
    "physical": "fill:#FBF0CC,color:#222",
    "logical":  "fill:#DCEAF7,color:#222",
    "boundary": "fill:#FFFFFF,color:#222",
}
IMPACT = {
    "high":   "stroke:#B03A2E,stroke-width:4px",
    "medium": "stroke:#D68910,stroke-width:3px",
    "low":    "stroke:#566573,stroke-width:2px",
    "none":   "stroke:#AAB7B8,stroke-width:1px,stroke-dasharray:4 3,opacity:0.6",
    "gap":    "stroke:#C0392B,stroke-width:3px,stroke-dasharray:6 4",
}


MAX_ELEMENTS = 5  # the full list is in the page's detail table


def nid(domain_id):
    return "D" + domain_id.split("-")[-1]


def render(model, edges="none"):
    """edges: none (worksheet heat map, default) | impacted | all"""
    """Return Mermaid text for a loaded BCA model dict."""
    tax = yaml.safe_load(open(ROOT / "library/taxonomy/domains.yaml", encoding="utf-8"))

    domains = {d["id"]: d for d in tax["domains"]}
    children = {}
    for d in tax["domains"]:
        children.setdefault(d["parent"], []).append(d["id"])

    impact = {i["domain"]: i for i in model["domain_impact"]}

    def level(did):
        i = impact.get(did)
        if i is None:
            return "gap"
        if i["impact"] == "none" and not i.get("confirmed_empty"):
            return "gap"
        return i["impact"]

    def label(did, container=False):
        d = domains[did]
        if container:  # one line, so the title does not overlap nested boxes
            parts = [f"<b>{d['name']}</b>"]  # IDs appear in the detail table
        else:
            parts = [f"<b>{d['name']}</b>", f"<small>{did}</small>"]
        if not container:
            els = [e["name"] if isinstance(e, dict) else str(e)
                   for e in impact.get(did, {}).get("elements", [])]
            shown = els[:MAX_ELEMENTS]
            if len(els) > MAX_ELEMENTS:
                shown.append(f"+{len(els) - MAX_ELEMENTS} more")
            parts += [f"• {e}" for e in shown]
        if level(did) == "gap":
            parts.append("<b>GAP: not assessed</b>" if did not in impact else "<b>GAP: unconfirmed</b>")
        return "<br/>".join(parts).replace('"', "'").replace("&", "#amp;")

    out = []
    title = model["metadata"]["title"]
    out += ["---", f"title: Domain Impact Worksheet - {title}", "---",
            "%% Generated by scripts/render_domain_impact.py. Do not edit.",
            "%% Domain model (c) Archistry / Andrew S. Townley, used with attribution. Based on SABSA(R).",
            "flowchart TB"]
    for k, v in FILL.items():
        out.append(f"  classDef {k} {v}")

    styles = []

    def emit(did, indent="  "):
        d = domains[did]
        kids = children.get(did, [])
        if kids:
            out.append(f'{indent}subgraph {nid(did)}["{label(did, container=True)}"]')
            out.append(f"{indent}  direction TB")
            for k in kids:
                emit(k, indent + "  ")
            out.append(f"{indent}end")
            styles.append(f"  style {nid(did)} {CONTAINER[d['type']]},{IMPACT[level(did)]}")
        else:
            out.append(f'{indent}{nid(did)}["{label(did)}"]:::{d["type"]}')
            styles.append(f"  style {nid(did)} {IMPACT[level(did)]}")

    for root in children.get(None, []):
        emit(root)

    # Invisible links stack the worksheet rows (heat-map layout).
    rows = tax.get("worksheet_layout", [])
    for upper, lower in zip(rows, rows[1:]):
        # Rows inside the enterprise stack under each other; the enterprise
        # box itself stacks above the external rows.
        for i, below in enumerate(lower):
            above = upper[min(i, len(upper) - 1)]
            if domains[below]["parent"] == domains[above]["parent"] or domains[above]["parent"] is None and domains[below]["parent"] is None:
                out.append(f"  {nid(above)} ~~~ {nid(below)}")

    impacted = {did for did in domains if level(did) not in ("none",)}
    for r in tax["relationships"]:
        if edges == "all" or (edges == "impacted" and r["from"] in impacted and r["to"] in impacted):
            out.append(f'  {nid(r["from"])} -- "{r["verb"]}" --> {nid(r["to"])}')

    out += ["", "  subgraph LEGEND[\"Legend\"]", "    direction LR",
            '    L1["Physical"]:::physical', '    L2["Logical"]:::logical',
            '    L3["High impact"]', '    L4["Medium"]', '    L5["Low"]',
            '    L6["Not impacted"]', '    L7["GAP"]', "  end"]
    styles += [f"  style L3 {IMPACT['high']}", f"  style L4 {IMPACT['medium']}",
               f"  style L5 {IMPACT['low']}", f"  style L6 {IMPACT['none']}",
               f"  style L7 {IMPACT['gap']}"]
    out += styles

    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("model")
    ap.add_argument("--edges", choices=["none", "impacted", "all"], default="none",
                    help="none = worksheet heat map (default); impacted/all = add relationship verbs")
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    model = yaml.safe_load(open(a.model, encoding="utf-8"))
    text = render(model, a.edges)
    if a.out:
        pathlib.Path(a.out).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
